import { Line } from ".";

export default {
  title: "Components/Line",
  component: Line,
  argTypes: {
    property1: {
      options: ["line"],
      control: { type: "select" },
    },
    property2: {
      options: ["system"],
      control: { type: "select" },
    },
    property3: {
      options: [
        "timer-flash-line",
        "delete-bin-line",
        "arrow-right-up-line",
        "arrow-left-down-line",
        "error-warning-line",
        "settings-4-line",
        "shield-star-line",
        "upload-line",
        "settings-3-line",
        "shield-flash-line",
        "share-forward-box-line",
        "alarm-warning-line",
        "delete-back-line",
        "upload-2-line",
        "menu-2-line",
        "checkbox-circle-line",
        "check-double-line",
        "shield-line",
        "arrow-drop-up-line",
        "arrow-down-line",
        "menu-unfold-line",
        "arrow-down-s-line",
        "star-half-s-line",
        "dashboard-line",
        "loader-line",
        "delete-bin-6-line",
        "shield-keyhole-line",
        "arrow-up-s-line",
        "question-line",
        "settings-6-line",
        "lock-unlock-line",
        "delete-bin-2-line",
        "filter-off-line",
        "logout-box-r-line",
        "arrow-right-line",
        "close-circle-line",
        "filter-2-line",
        "arrow-up-down-line",
        "history-line",
        "checkbox-multiple-blank-line",
        "list-settings-line",
        "download-2-line",
        "delete-bin-3-line",
        "arrow-down-circle-line",
        "upload-cloud-2-line",
        "menu-line",
        "alarm-line",
        "divide-line",
        "logout-circle-r-line",
        "delete-bin-7-line",
        "arrow-right-down-line",
        "search-line",
        "external-link-line",
        "logout-circle-line",
        "spam-2-line",
        "more-line",
        "star-s-line",
        "arrow-go-back-line",
        "menu-fold-line",
        "menu-4-line",
        "timer-2-line",
        "search-eye-line",
        "alert-line",
        "zoom-in-line",
        "eye-close-line",
        "star-half-line",
        "timer-line",
        "apps-line",
        "menu-3-line",
        "time-line",
        "add-line",
        "checkbox-indeterminate-line",
        "download-cloud-2-line",
        "toggle-line",
        "download-cloud-line",
        "thumb-down-line",
        "close-line",
        "arrow-right-circle-line",
        "download-line",
        "lock-line",
        "forbid-line",
        "arrow-right-s-line",
        "forbid-2-line",
        "settings-5-line",
        "arrow-up-circle-line",
        "more-2-line",
        "logout-box-line",
        "share-forward-line",
        "delete-bin-5-line",
        "filter-line",
        "check-line",
        "zoom-out-line",
        "notification-badge-line",
        "lock-2-line",
        "menu-add-line",
        "search-2-line",
        "arrow-left-up-line",
        "checkbox-multiple-line",
        "find-replace-line",
        "arrow-left-s-line",
        "arrow-left-circle-line",
        "checkbox-blank-line",
        "delete-bin-4-line",
        "arrow-go-forward-line",
        "eye-2-line",
        "refresh-line",
        "settings-line",
        "menu-5-line",
        "filter-3-line",
        "settings-2-line",
        "checkbox-blank-circle-line",
        "arrow-drop-right-line",
        "add-box-line",
        "information-line",
        "share-forward-2-line",
        "upload-cloud-line",
        "arrow-left-line",
        "arrow-drop-left-line",
        "shield-user-line",
        "lock-password-line",
        "loader-4-line",
        "radio-button-line",
        "arrow-left-right-line",
        "login-circle-line",
        "arrow-drop-down-line",
        "subtract-line",
        "checkbox-line",
        "apps-2-line",
        "share-circle-line",
        "eye-off-line",
        "loader-3-line",
        "shield-check-line",
        "thumb-up-line",
        "spam-3-line",
        "shield-cross-line",
        "share-box-line",
        "side-bar-line",
        "indeterminate-circle-line",
        "spam-line",
        "login-box-line",
        "loader-2-line",
        "function-line",
        "loader-5-line",
        "delete-back-2-line",
        "add-circle-line",
        "arrow-up-line",
        "eye-line",
        "share-line",
        "star-line",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    property1: "line",
    property2: "system",
    property3: "timer-flash-line",
    className: {},
    propertyLine: "/img/property-1-line-property-2-system-property-3-checkbox-circle-l.svg",
  },
};
