import { Solid } from ".";

export default {
  title: "Components/Solid",
  component: Solid,
  argTypes: {
    property1: {
      options: ["fill"],
      control: { type: "select" },
    },
    property2: {
      options: ["system"],
      control: { type: "select" },
    },
    property3: {
      options: [
        "timer-fill",
        "list-settings-fill",
        "arrow-drop-up-fill",
        "delete-bin-7-fill",
        "loader-2-fill",
        "settings-5-fill",
        "arrow-drop-right-fill",
        "arrow-left-up-fill",
        "arrow-right-up-fill",
        "more-2-fill",
        "notification-badge-fill",
        "arrow-drop-down-fill",
        "upload-fill",
        "eye-2-fill",
        "share-forward-2-fill",
        "share-forward-box-fill",
        "side-bar-fill",
        "arrow-left-s-fill",
        "arrow-go-back-fill",
        "arrow-down-s-fill",
        "filter-off-fill",
        "delete-bin-6-fill",
        "logout-box-r-fill",
        "settings-fill",
        "menu-3-fill",
        "forbid-2-fill",
        "logout-circle-r-fill",
        "menu-fold-fill",
        "arrow-right-s-fill",
        "close-fill",
        "download-cloud-2-fill",
        "check-fill",
        "question-fill",
        "menu-5-fill",
        "loader-3-fill",
        "menu-add-fill",
        "delete-bin-2-fill",
        "loader-4-fill",
        "delete-bin-5-fill",
        "arrow-down-circle-fill",
        "alarm-warning-fill",
        "external-link-fill",
        "arrow-left-right-fill",
        "upload-2-fill",
        "share-forward-fill",
        "check-double-fill",
        "checkbox-multiple-blank-fill",
        "menu-2-fill",
        "subtract-fill",
        "arrow-right-circle-fill",
        "login-box-fill",
        "delete-bin-4-fill",
        "add-box-fill",
        "shield-check-fill",
        "settings-6-fill",
        "star-fill",
        "toggle-fill",
        "shield-keyhole-fill",
        "arrow-left-fill",
        "logout-circle-fill",
        "refresh-fill",
        "delete-back-2-fill",
        "upload-cloud-fill",
        "filter-3-fill",
        "find-replace-fill",
        "menu-unfold-fill",
        "add-circle-fill",
        "information-fill",
        "dashboard-fill",
        "thumb-up-fill",
        "forbid-fill",
        "checkbox-multiple-fill",
        "spam-2-fill",
        "filter-2-fill",
        "arrow-left-down-fill",
        "radio-button-fill",
        "lock-password-fill",
        "thumb-down-fill",
        "apps-fill",
        "delete-bin-fill",
        "checkbox-fill",
        "spam-fill",
        "arrow-up-circle-fill",
        "arrow-down-fill",
        "divide-fill",
        "loader-5-fill",
        "menu-fill",
        "upload-cloud-2-fill",
        "share-circle-fill",
        "indeterminate-circle-fill",
        "search-2-fill",
        "history-fill",
        "shield-fill",
        "loader-fill",
        "login-circle-fill",
        "checkbox-circle-fill",
        "add-fill",
        "share-fill",
        "arrow-right-down-fill",
        "checkbox-indeterminate-fill",
        "error-warning-fill",
        "lock-2-fill",
        "search-fill",
        "star-half-fill",
        "zoom-out-fill",
        "timer-flash-fill",
        "delete-back-fill",
        "close-circle-fill",
        "download-fill",
        "arrow-up-fill",
        "delete-bin-3-fill",
        "star-half-s-fill",
        "menu-4-fill",
        "zoom-in-fill",
        "settings-2-fill",
        "arrow-left-circle-fill",
        "download-cloud-fill",
        "arrow-right-fill",
        "search-eye-fill",
        "settings-3-fill",
        "lock-unlock-fill",
        "apps-2-fill",
        "download-2-fill",
        "arrow-go-forward-fill",
        "eye-off-fill",
        "arrow-up-s-fill",
        "timer-2-fill",
        "alarm-fill",
        "shield-flash-fill",
        "star-s-fill",
        "logout-box-fill",
        "shield-cross-fill",
        "arrow-up-down-fill",
        "shield-user-fill",
        "checkbox-blank-fill",
        "spam-3-fill",
        "shield-star-fill",
        "eye-close-fill",
        "filter-fill",
        "share-box-fill",
        "arrow-drop-left-fill",
        "more-fill",
        "checkbox-blank-circle-fill",
        "lock-fill",
        "settings-4-fill",
        "time-fill",
        "alert-fill",
        "eye-fill",
        "function-fill",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    property1: "fill",
    property2: "system",
    property3: "timer-fill",
    className: {},
    propertyFill: "/img/property-1-fill-property-2-system-property-3-arrow-down-s-fill.svg",
  },
};
